### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jhonatan-Souza** [nchlis/image_captioning#1]
I try to run generate_new_caption.py and the following error appeared.

  File "generate_new_caption.py", line 129, in <module>
    X_enc=model.predict(x).reshape((1,P))#encode the image
ValueError: cannot reshape array of size 100352 into shape (1,2048)

**Comment by nchlis** [comment]
I just reproduced the results and it's working normally for me.
This is probably a mismatch between package versions.

The code in this repo uses tensorflow 1.4.0 and keras 2.1.1.
